export const POKEMON = {
    GET_POKEMON_LIST: 'GET_POKEMON_LIST',
    GET_POKEMON_LIST_BEGIN: 'GET_POKEMON_LIST_BEGIN',
    GET_POKEMON_LIST_SUCCESS: 'GET_POKEMON_LIST_SUCCESS',
    GET_POKEMON_LIST_ERROR: 'GET_POKEMON_LIST_ERROR',
    POKEMON_FILTER_SUCCESS: 'POKEMON_FILTER_SUCCESS'
}